# Generated by Django 5.2.4 on 2025-07-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=42.8746, help_text='Latitude coordinate for map display', max_digits=9),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=74.5698, help_text='Longitude coordinate for map display', max_digits=9),
        ),
    ]
